# SPRING DATASOURCE CONFIG (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root


# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# RABBITMQ CONFIG
spring.rabbitmq.host=shark.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=igpybkom
spring.rabbitmq.password=zVxniO3dRd9E5UVY7Gz3_anFbEXwto5o
spring.rabbitmq.virtual-host=igpybkom

# SPRINGDOC SWAGGER CONFIG
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# SERVER CONFIG
server.port=8081
